### ISSUE TITLE
save in the pickle the variables needed vs. saving them in the filename

### ISSUE THREAD

**Issue by antgonza** [biocore/evident#4]
Currently we are saving as part of the filename: "distance/alpha-filename + metadata-filename + metadata-column + iteration" and the idea is to save that as part of the full pickle and use random (20 random a-zA-Z unique) filenames for the outputs.

**Comment by serenejiang** [comment]
Hi, Antonio. I was using "join([random.choice(string.ascii_letters) for n in range(20)])" to generate the random filenames consisted of 20 characters. Several questions encountered: 1. this function will generate a different filename each time. Although it's unlikely that filenames will be duplicated, I am wondering whether there is a better way to ensure that all filenames are unique; 2. since filenames are random, even for the same effect size calculation, the filename will be different. Do we want to avoid duplicated calculation? 3. my current code can generate random filenames and store the original file information (alpha-filename, metadata-filename and metadata-column) in the pickle file, but it's impossible to tell which file is related to which effect size calculation by just looking at the new filenames. Hence, the previous unit testing code couldn't run, as I need to know which file is related to which calculation.  Any suggestion?

**Comment by serenejiang** [comment]
Also, for the sake of calculating pooled p-values later, we also need meaning filenames so that we can pull out the desired raw p-values from specific file.

**Comment by antgonza** [comment]
A. I was using "join([random.choice(string.ascii_letters) for n in range(20)])": sounds good.
B. Questions encountered:
1. right, and normally a simple while loop checking/regenerating the name in case it exist suffices
2. yes, we want to avoid duplication of calculations and the reason that we need to save the required values within the pickle ("save in the pickle the variables needed"). This will also meant that now the check will open the available pickles, check which ones have been processed and process those that haven't been created.
3. IMOO, at this time, is fine that the files are not human readable as long as point 2 works fine.
4. Well, we need the information and that information currently is part of the filename, right? Anyway, the idea of this issue is to move those save those values within the pickle so we don't need to assume/parse filenames. 

Let me know if you want to have a call to discuss this further ...

Thanks.

**Comment by serenejiang** [comment]
Yoshiki recommended me to use md5 for the random filename, so I used your original filename and convert them to random number with strings by md5. In this way, I could get unique random filename for each job, and I was able to trace the job by the md5 name as well.
